import { useState } from "react";
import { Check, Copy, FileText, X } from "lucide-react";
import type { Approval, JiraIssue, KubernetesNode, Release, ReleasePackage, Risk } from "../../types";
import { useToastStore } from "../../store/useToastStore";

interface ExecutiveBriefingModalProps {
  isOpen: boolean;
  onClose: () => void;
  release: Release;
  jiraIssues: JiraIssue[];
  packages: ReleasePackage[];
  approvals: Approval[];
  risks: Risk[];
  nodes: KubernetesNode[];
  readinessScore: number;
}

export function ExecutiveBriefingModal({
  isOpen,
  onClose,
  release,
  jiraIssues,
  packages,
  approvals,
  risks,
  nodes,
  readinessScore,
}: ExecutiveBriefingModalProps) {
  const showToast = useToastStore((state) => state.showToast);
  const [copied, setCopied] = useState(false);

  if (!isOpen) return null;

  const approvedCount = approvals.filter((a) => a.status === "Approved").length;
  const openRisks = risks.filter((r) => r.status === "Open");
  const unhealthyNodes = nodes.filter((n) => n.status !== "Healthy");

  const markdownContent = `# 🚀 Release Readiness Briefing: ${release.name} (${release.version})
**Release ID:** ${release.id}  
**Environment:** ${release.environment}  
**Target Deployment Date:** ${release.targetDate}  
**Release Manager:** ${release.releaseManager}  
**Readiness Score:** ${readinessScore}%  

---

## 📊 Executive Summary
${release.description}

- **Overall Health:** ${readinessScore >= 80 ? "🟢 READY FOR DEPLOYMENT" : readinessScore >= 50 ? "🟡 AT RISK / ATTENTION NEEDED" : "🔴 DEPLOYMENT BLOCKED"}
- **Governance Sign-offs:** ${approvedCount} of ${approvals.length} gates approved.
- **Infrastructure Status:** ${unhealthyNodes.length === 0 ? "All assigned cluster nodes healthy" : `⚠️ ${unhealthyNodes.length} node(s) unhealthy`}

---

## 🛡️ Governance & Approval Gates
${approvals
  .map(
    (a) =>
      `- [${a.status === "Approved" ? "x" : " "}] **${a.type}**: ${a.status} (Approver: ${a.approver || "Pending"}, Due: ${a.dueDate.slice(0, 10)})`,
  )
  .join("\n")}

---

## 📦 Deployment Packages
${packages.map((p) => `- **${p.name}** (v${p.version}) - Type: ${p.type} [Status: ${p.status}]`).join("\n") || "None specified"}

---

## 📋 Linked Jira Issues (${jiraIssues.length})
${jiraIssues.map((j) => `- **${j.key}**: ${j.summary} (${j.priority} | ${j.status})`).join("\n") || "None linked"}

---

## ⚠️ Open Risks & Mitigations
${
  openRisks.length === 0
    ? "✅ Zero open critical or high risks."
    : openRisks.map((r) => `- **${r.title}** (${r.severity}): ${r.mitigation}`).join("\n")
}

---
*Generated by ReleaseOps Intelligence on ${new Date().toUTCString()}*
`;

  const handleCopy = () => {
    navigator.clipboard.writeText(markdownContent);
    setCopied(true);
    showToast({
      variant: "success",
      title: "Copied to clipboard",
      description: "Executive release briefing copied as Markdown.",
    });
    setTimeout(() => setCopied(false), 2000);
  };

  return (
    <div className="fixed inset-0 z-50 flex items-center justify-center bg-slate-900/50 p-4 backdrop-blur-sm">
      <div className="animate-command-palette-in flex max-h-[85vh] w-full max-w-2xl flex-col overflow-hidden rounded-2xl border border-slate-200 bg-white shadow-2xl dark:border-slate-700 dark:bg-slate-800">
        <div className="flex items-center justify-between border-b border-slate-100 px-6 py-4 dark:border-slate-700">
          <div className="flex items-center gap-2.5">
            <div className="flex h-8 w-8 items-center justify-center rounded-lg bg-blue-600 text-white">
              <FileText className="h-4 w-4" />
            </div>
            <div>
              <h2 className="text-base font-semibold text-slate-900 dark:text-slate-100">
                Executive Release Briefing
              </h2>
              <p className="text-xs text-slate-500 dark:text-slate-400">
                Automated Markdown briefing for stakeholder communication and CAB reviews
              </p>
            </div>
          </div>
          <button
            type="button"
            onClick={onClose}
            className="rounded-lg p-1 text-slate-400 hover:bg-slate-100 hover:text-slate-600 dark:hover:bg-slate-700 dark:hover:text-slate-200"
          >
            <X className="h-5 w-5" />
          </button>
        </div>

        <div className="flex-1 overflow-y-auto p-6">
          <pre className="rounded-xl border border-slate-200 bg-slate-50 p-4 text-xs font-mono text-slate-800 whitespace-pre-wrap dark:border-slate-700 dark:bg-slate-900 dark:text-slate-200">
            {markdownContent}
          </pre>
        </div>

        <div className="flex items-center justify-between border-t border-slate-100 px-6 py-3.5 dark:border-slate-700">
          <p className="text-xs text-slate-500 dark:text-slate-400">
            Includes governance sign-offs, risk factors, and node telemetry
          </p>
          <div className="flex gap-2">
            <button
              type="button"
              onClick={onClose}
              className="rounded-lg border border-slate-200 px-3.5 py-1.5 text-xs font-medium text-slate-600 hover:bg-slate-50 dark:border-slate-600 dark:text-slate-300 dark:hover:bg-slate-700"
            >
              Close
            </button>
            <button
              type="button"
              onClick={handleCopy}
              className="flex items-center gap-1.5 rounded-lg bg-blue-600 px-3.5 py-1.5 text-xs font-semibold text-white hover:bg-blue-700 shadow transition-all"
            >
              {copied ? <Check className="h-3.5 w-3.5" /> : <Copy className="h-3.5 w-3.5" />}
              {copied ? "Copied" : "Copy Markdown"}
            </button>
          </div>
        </div>
      </div>
    </div>
  );
}
